# Creating Array

In [1]:
!pip install numpy

In [4]:
import numpy as np
n1= np.array([3,4,5,6,8])
print(n1)

[3 4 5 6 8]


In [7]:
n2 = np.array([[1,2,3,4],[5,6,7,8]])
print(n2)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
n3=np.zeros([10,10])
print(n3)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [12]:
n4=np.zeros([10,10],dtype="int32")
print(n4)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [40]:
n5=np.ones([10,2,2],dtype="int32")
print(n5)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [26]:
n6=np.empty([3,2,2],dtype="int32")
print(n6)

[[[4128860 6029375]
  [7274573 7209077]]

 [[5242996 6881391]
  [7602286 6357069]]

 [[6357102 6619239]
  [    114 3407973]]]


# Arange and Linspace

In [19]:
n7=np.arange(9)
print(n7)

[0 1 2 3 4 5 6 7 8]


In [22]:
n8=np.linspace(0,20,num=30,dtype="int32")
print(n8)

[ 0  0  1  2  2  3  4  4  5  6  6  7  8  8  9 10 11 11 12 13 13 14 15 15
 16 17 17 18 19 20]


# Full and Fill

In [24]:
n9=np.full([2,3],99)
print(n9)

[[99 99 99]
 [99 99 99]]


In [27]:
n6.fill(10)
print(n6)

[[[10 10]
  [10 10]]

 [[10 10]
  [10 10]]

 [[10 10]
  [10 10]]]


# Accessing array elements

In [28]:
print(n1[0])

3


In [29]:
print(n1[-1])

8


In [30]:
print(n2[1,3])

8


In [33]:
print(n2[0])

[1 2 3 4]


In [35]:
print(n2[:,3])

[4 8]


In [41]:
n5[1,1,1]=25
print(n5)

[[[ 1  1]
  [ 1  1]]

 [[ 1  1]
  [ 1 25]]

 [[ 1  1]
  [ 1  1]]

 [[ 1  1]
  [ 1  1]]

 [[ 1  1]
  [ 1  1]]

 [[ 1  1]
  [ 1  1]]

 [[ 1  1]
  [ 1  1]]

 [[ 1  1]
  [ 1  1]]

 [[ 1  1]
  [ 1  1]]

 [[ 1  1]
  [ 1  1]]]


# Size and Shape

In [43]:
print(n5.ndim)
print(n1.ndim)

3
1


In [44]:
print(n5.shape)
print(n1.shape)

(10, 2, 2)
(5,)


In [45]:
print(n5.size)

40


In [47]:
print(n5.dtype)

int32


In [48]:
print(n5.itemsize)

4


In [49]:
print(n5.nbytes)

160


# Sorting

In [51]:
n10 = np.array([5,3,7,5,6,97,5,566,1])
np.sort(n10)

array([  1,   3,   5,   5,   5,   6,   7,  97, 566])

In [53]:
n11=np.array([[3,1,8],[6,2,4]])
np.sort(n11)

array([[1, 3, 8],
       [2, 4, 6]])

In [54]:
np.sort(n11,axis=0)

array([[3, 1, 4],
       [6, 2, 8]])

# Reshaping and Array Conversion

In [55]:
n12=n10.reshape(3,3)
print(n12)

[[  5   3   7]
 [  5   6  97]
 [  5 566   1]]


In [59]:
n13=np.arange(4)
n14=np.arange(5,9)
n15=np.concatenate((n13,n14))
print(n15)

[0 1 2 3 5 6 7 8]


In [64]:
n16=np.arange(8)
n17=n16[np.newaxis,:]
print(n17)
print(n17.shape)
n18=n16[:,np.newaxis]
print(n18)
print(n18.shape)

[[0 1 2 3 4 5 6 7]]
(1, 8)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
(8, 1)


In [67]:
n19=np.expand_dims(n16,axis=0)
print(n19)
n20=np.expand_dims(n16,axis=1)
print(n20)

[[0 1 2 3 4 5 6 7]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


# Indexing and Slicing

In [68]:
n21=np.arange(10)
print(n21)
print(n21[n21<5])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [70]:
print(n21[(n21>3) & (n21<8)])

[4 5 6 7]


In [72]:
fiveup=n21>5
print(fiveup)
print(n21[fiveup])

[False False False False False False  True  True  True  True]
[6 7 8 9]


In [78]:
print(np.nonzero(n21>5))

(array([6, 7, 8, 9], dtype=int64),)


In [79]:
print(n21[3:7])

[3 4 5 6]


# Stack and Split

In [80]:
n22=np.array([[1,2],[3,4]])
n23=np.array([[5,6],[7,8]])
np.hstack((n22,n23))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [81]:
np.vstack((n22,n23))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [87]:
n24=np.arange(20)
np.hsplit(n24,4)

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19])]

In [92]:
n25=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.vsplit(n25,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

# Copy

In [98]:
n26=n24.copy()
n26[1]=20
print(f"{n24}\n{n26}")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0 20  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


# Math

In [100]:
print(n22)
print(n23)
print(n22+n23)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]


In [101]:
print(n26)
print(n26.sum())

[ 0 20  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
209


In [102]:
print(n26.max())

20


In [103]:
print(n26.min())

0


In [106]:
print(n26*10)
print((n26*10).sum())

[  0 200  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170
 180 190]
2090


In [112]:
print(np.cos(n26))

[ 1.          0.40808206 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257
  0.84385396  0.90744678  0.13673722 -0.75968791 -0.95765948 -0.27516334
  0.66031671  0.98870462]


# Random Numbers

In [109]:
np.random.rand(3,3)

array([[0.4217838 , 0.74341565, 0.12405161],
       [0.52406741, 0.2851054 , 0.34504861],
       [0.18032697, 0.65472325, 0.51677837]])

In [111]:
np.random.randint(1000,size=(3,3))

array([[825,  41, 853],
       [535, 283, 700],
       [589, 408, 977]])